version: "3.3"
services:

  whoami-1:
    image: jwilder/whoami
    hostname: whoami-1
    ports:
      - 8001:8000

  whoami-2:
    image: jwilder/whoami
    hostname: whoami-2
    ports:
      - 8002:8000

  haproxy:
    build: ./
    image: dcagatay/env-haproxy:latest
    environment:
      LB_TYPE: "HTTP"
      BIND_PORT: "8181"
      LB_SERVER_1: "whoami-1:8000"
      LB_SERVER_2: "whoami-2:8000"
    ports:
      - 8181:8181
      - 8404:8404
    restart: unless-stopped
